

export const Sample_Plces:any[]=[
    {
        id: '1',
        name: 'INDIA',
        price: 10000,
        stars: 4.5,
        imageUrl: 'assets/images/India.jpg',
        backgroundUrl: 'assets/images/BackgroundIndia.jpg',
        duration: "5 days",
        tags:['Agra','manali','varanasi','Goa','Munnar','Ooty','Thiruvananthapuram','Kochi','Mysore','Visakhapatnam','Hyderabad'],
        content:[' Experience the Timeless Wonder of the Taj Mahal : The Taj Mahal, located in Agra, India, is a UNESCO World Heritage Site and one of the New Seven Wonders of the World. Built by Mughal Emperor Shah Jahan in memory of his beloved wife Mumtaz Mahal, it is renowned for its breathtaking beauty and intricate architecture. Constructed from white marble and adorned with delicate inlays of semi-precious stones, the Taj Mahal is a symbol of eternal love and a masterpiece of Mughal artistry. Visitors can explore its perfectly symmetrical layout, marvel at its towering domes, and admire the exquisite marble lattice work that adorns the central mausoleum. Whether at dawn, when it glows in golden light, or at sunset, when it blushes with hues of pink and orange, the Taj Mahal offers unforgettable views and a serene atmosphere. A visit to this timeless wonder promises to be an enriching and awe-inspiring experience for travelers of all interests.',
        ' Manali, nestled in the scenic mountains of Himachal Pradesh, India, is a popular hill station renowned for its breathtaking natural beauty and adventurous activities. Visitors flock to Manali to enjoy activities such as trekking, skiing, paragliding, and river rafting amidst the stunning landscapes of snow-capped peaks, lush valleys, and meandering rivers.',
        'Varanasi, one of the oldest cities in the world and the spiritual capital of India, is situated on the banks of the sacred Ganges River. Known for its ghats, temples, and vibrant culture, Varanasi attracts pilgrims and tourists alike who come to witness mesmerizing Ganga Aarti ceremonies, explore narrow alleys bustling with life, and immerse themselves in the citys rich spiritual heritage.',
        'Goa, located on the western coast of India, is famous for its pristine beaches, vibrant nightlife, and Portuguese heritage. Visitors to Goa can relax on sandy shores, explore ancient churches and temples, indulge in water sports, savor delicious seafood, and experience the lively atmosphere of its beach shacks and nightclubs.',
        'Munnar, located in the Western Ghats mountain range of Kerala, India, is a picturesque hill station renowned for its lush tea plantations, mist-covered hills, and scenic beauty. Visitors to Munnar can enjoy trekking through verdant landscapes, visit tea factories to learn about tea production, spot exotic wildlife in national parks, and rejuvenate amidst the serene ambiance of nature.',
        'Ooty, also known as Udhagamandalam, is a charming hill station nestled in the Nilgiri Hills of Tamil Nadu, India. Famous for its pleasant climate, sprawling tea gardens, and colonial-era architecture, Ooty is a popular retreat for nature lovers and honeymooners. Visitors can explore botanical gardens, embark on scenic train rides, indulge in outdoor activities, and enjoy panoramic views of the surrounding hills.',
        'Thiruvananthapuram, the capital city of Kerala, India, is a vibrant metropolis known for its rich cultural heritage, colonial architecture, and idyllic beaches. Visitors to Thiruvananthapuram can explore historic landmarks such as the Padmanabhaswamy Temple and Napier Museum, relax on sandy shores, indulge in authentic Kerala cuisine, and experience the laid-back charm of this coastal city.',
        'Kochi, also known as Cochin, is a bustling port city situated on the southwest coast of India. Renowned for its eclectic blend of cultures, historic landmarks, and scenic backwaters, Kochi offers visitors a fascinating glimpse into its colonial past and maritime heritage. Tourists can explore ancient forts, bustling markets, serene backwaters, and enjoy traditional Kathakali performances.',
        'Mysore, located in the southern state of Karnataka, India, is a city steeped in history, culture, and royalty. Famous for its grand Mysore Palace, vibrant Dasara festival, and intricate silk sarees, Mysore attracts visitors with its regal charm and architectural marvels. Tourists can explore ornate palaces, lush gardens, bustling markets, and savor the citys unique culinary delights.',
        'Visakhapatnam, often referred to as Vizag, is a coastal city located in the southeastern state of Andhra Pradesh, India. Known for its natural beauty, pristine beaches, and bustling ports, Visakhapatnam offers visitors a perfect blend of urban vibrancy and scenic tranquility. Tourists can explore historic landmarks, relax on sandy shores, indulge in water sports, and savor delicious seafood.',
        'Hyderabad, the capital city of Telangana state in southern India, is a vibrant metropolis steeped in history, culture, and culinary delights. Known as the \'City of Pearls\' and the \'City of Nizams\', Hyderabad boasts architectural wonders such as the Charminar and Golconda Fort, vibrant bazaars selling traditional crafts, and mouthwatering Hyderabadi cuisine, including the famous biryani.',
    ],
    lats:[27.1767,32.2396, 25.3176,15.2993,10.0889,11.4064, 8.5241,9.9312,12.2958,17.6868,17.3850],
    lngs:[78.0081,  77.1887, 82.9739, 74.1240,77.0595, 76.6932,76.9366, 76.2673,76.6394,83.2185, 78.4867],
    },
    {
        id: '2',
        name: 'France',
        price: 100000,
        stars: 4.5,
        imageUrl: 'assets/images/France.jpg',
        duration: "5 days",
        tags: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame Cathedra','Palace of Versailles','french riviera','Arc de Triomphe'],
        backgroundUrl: 'assets/images/BackgroundFrance.jpg',
        content: ['The Eiffel Tower, an iconic symbol of France and one of the most recognizable landmarks in the world, stands majestically in the heart of Paris. Designed by Gustave Eiffel, this wrought-iron lattice tower was completed in 1889 for the Exposition Universelle (World\'s Fair). Rising to a height of 324 meters, the Eiffel Tower offers breathtaking panoramic views of the Paris skyline from its observation decks. Visitors can ascend the tower via elevators or stairs and admire its intricate lattice structure, illuminated beautifully at night. Whether seen during the day or illuminated against the Parisian skyline at night, the Eiffel Tower continues to captivate millions of visitors each year with its timeless beauty and romantic allure',
            'The Louvre Museum, located in the heart of Paris, is the largest art museum in the world and a historic monument of French culture. Housed in the former royal palace of the Louvre, this magnificent museum is home to thousands of works of art spanning from antiquity to the present day. Among its most famous treasures are iconic masterpieces such as Leonardo da Vinci\'s Mona Lisa, the Venus de Milo, and the Winged Victory of Samothrace. Visitors can wander through its vast galleries and admire a diverse array of paintings, sculptures, decorative arts, and archaeological artifacts. With its rich cultural heritage and unparalleled collection, the Louvre Museum offers an unforgettable journey through art history.',
            'Notre-Dame Cathedral, a masterpiece of French Gothic architecture, is a symbol of Paris and one of the most famous cathedrals in the world. Located on the Île de la Cité, this historic landmark dates back to the 12th century and is renowned for its stunning facade, imposing towers, and intricate rose windows. Visitors can marvel at its soaring nave, intricate sculptures, and majestic organ during a visit to this sacred place. While tragically damaged by a fire in 2019, ongoing restoration efforts aim to preserve and restore Notre-Dame to its former glory, ensuring that future generations can continue to admire its timeless beauty and architectural significance.',
            'The Palace of Versailles, a symbol of French royal grandeur and opulence, is one of the most magnificent palaces in the world. Located in the Île-de-France region, this UNESCO World Heritage site was the principal residence of the French monarchy from the time of Louis XIV until the French Revolution. Visitors can explore its lavish apartments, including the Hall of Mirrors, the King\'s and Queen\'s Grand Apartments, and the stunning gardens designed by André Le Nôtre. The palace\'s rich history, exquisite architecture, and sumptuous interiors offer a glimpse into the extravagance of the French monarchy and the cultural legacy of the Ancien Régime.',
            'The French Riviera, also known as the Côte d\'Azur, is a glamorous and sun-kissed stretch of coastline along the Mediterranean Sea. Renowned for its stunning beaches, luxurious resorts, and vibrant nightlife, the French Riviera has long been a playground for the rich and famous. Cities like Nice, Cannes, and Saint-Tropez epitomize the Riviera\'s chic and cosmopolitan lifestyle, attracting visitors from around the world with their beautiful beaches, elegant promenades, and exclusive boutiques. Whether relaxing on the beach, exploring charming seaside towns, or savoring exquisite cuisine, the French Riviera offers a quintessentially Mediterranean experience of sun, sea, and sophistication.',
            'The Arc de Triomphe is a monumental triumphal arch located at the western end of the Champs-Élysées in Paris. Commissioned by Napoleon Bonaparte in 1806 to commemorate his military victories, this iconic landmark stands as a symbol of France\'s military prowess and national pride. Rising to a height of 50 meters, the Arc de Triomphe features intricate reliefs, sculptures, and inscriptions celebrating France\'s military history. Visitors can ascend to the top of the arch for panoramic views of Paris, including the Eiffel Tower, the Louvre, and the bustling streets below. With its imposing presence and historic significance, the Arc de Triomphe remains a timeless symbol of French identity and resilience.',
        ],
        lats:[48.8584,48.8606,48.8530,48.8049,43.7102,48.8738],
        lngs:[2.2945, 2.3376, 2.3498, 2.1204,7.2620, 2.2950],
    },
    {
        id: '3',
        name: 'Italy',
        price: 10000,
        stars: 4.5,
        imageUrl: 'assets/images/Italy.jpg',
        backgroundUrl:'assets/images/BackgroundItaly.jpg',
        duration: "5 days",
        tags: ['Rome', 'Venice Canals', 'Florence Cathedral','Cinque Terre','Pompeii Archaeological Site'],
        content: ['The Colosseum, an iconic symbol of ancient Rome, is the largest amphitheater ever built. Constructed in 70-80 AD, this majestic structure once hosted gladiatorial contests, animal hunts, and public spectacles. Visitors can explore its impressive ruins, imagining the grandeur of ancient Roman entertainment and marveling at its architectural splendor.',
        'Venice, known as the "City of Canals," is renowned for its picturesque waterways, charming bridges, and elegant architecture. Visitors can take romantic gondola rides along the meandering canals, admiring historic landmarks such as the Rialto Bridge and St. Mark\'s Basilica. The enchanting atmosphere of Venice\'s winding streets and shimmering waterways makes it a favorite destination for lovers and adventurers alike.',
        'The Florence Cathedral, also known as the Duomo, is a magnificent example of Renaissance architecture and a symbol of Florence\'s cultural heritage. With its iconic dome designed by Filippo Brunelleschi, the cathedral dominates the city\'s skyline. Visitors can climb to the top of the dome for panoramic views of Florence or admire its stunning facade adorned with intricate marble designs and sculptures.',
        'Cinque Terre, a UNESCO World Heritage site, comprises five picturesque villages nestled along the rugged coastline of the Italian Riviera. Characterized by colorful houses perched on cliffs overlooking the Ligurian Sea, Cinque Terre offers breathtaking views, scenic hiking trails, and charming seaside cafes. Visitors can explore the quaint streets of each village, savoring fresh seafood and local wines while immersing themselves in the beauty of this coastal paradise.',
        'Pompeii, an ancient Roman city buried by the eruption of Mount Vesuvius in 79 AD, offers a fascinating glimpse into the past. Excavated ruins reveal well-preserved streets, buildings, and artifacts frozen in time. Visitors can wander through ancient streets, exploring Roman villas, bathhouses, and amphitheaters while learning about daily life in Pompeii before its catastrophic destruction. This archaeological site provides a unique opportunity to experience the legacy of ancient Rome firsthand.',
    ],
    lats:[41.8902,45.4408,43.7735,44.1284,40.7510],
    lngs:[ 12.4922, 12.3155 , 11.2558,9.7126,14.4924],
    },
    {
        id: '4',
        name: 'United States',
        price: 10000,
        stars: 4.5,
        imageUrl: 'assets/images/Usa.jpg',
        backgroundUrl:'assets/images/BackgroundUsa.jpg',
        duration: "5 days",
        tags: ['Grand Canyon, Arizona', 'Statue of Liberty, New York', 'Yellowstone National Park, Wyoming','Disneyland Resort, California','Times Square, New York'],
        content: ['The Grand Canyon, carved by the Colorado River, is one of the most breathtaking natural wonders in the world. Its immense size, colorful rock formations, and stunning vistas attract millions of visitors each year. Travelers can explore the canyon\'s rim on foot or by mule, hike into its depths, or experience the awe-inspiring views from helicopter tours. Sunset and sunrise at the Grand Canyon offer spectacular displays of light and shadow, making it a must-see destination for nature lovers and adventure seekers alike.',
            'A symbol of freedom and democracy, the Statue of Liberty stands tall on Liberty Island in New York Harbor. Given as a gift to the United States from France in 1886, Lady Liberty welcomes visitors with her torch held high and her iconic crown. Visitors can take a ferry to Liberty Island and climb to the statue\'s pedestal or crown for panoramic views of New York City and the surrounding harbor. The Statue of Liberty Museum offers exhibits on the statue\'s history and significance, providing insight into this enduring symbol of liberty and hope.',
            'Yellowstone National Park, America\'s first national park, is renowned for its geothermal wonders, diverse wildlife, and stunning natural landscapes. Visitors can marvel at the park\'s iconic geysers, including Old Faithful, which erupts with impressive regularity. Hiking trails lead to dramatic waterfalls, colorful hot springs, and bubbling mud pots, while wildlife enthusiasts can spot bison, elk, bears, and wolves roaming the park\'s vast wilderness. With its spectacular scenery and unique geological features, Yellowstone offers endless opportunities for exploration and adventure in the heart of the American West.',
            'Disneyland Resort, located in Anaheim, California, is a magical destination for families and Disney enthusiasts of all ages. Home to two theme parks—Disneyland Park and Disney California Adventure—this iconic resort offers immersive experiences, thrilling attractions, and beloved Disney characters. Visitors can explore classic attractions like Sleeping Beauty Castle, Space Mountain, and Pirates of the Caribbean, or discover new adventures in Pixar Pier and Star Wars: Galaxy\'s Edge. With enchanting parades, spectacular fireworks shows, and world-class entertainment, Disneyland Resort brings the magic of Disney to life in the heart of Southern California.',
            'Times Square, often referred to as "The Crossroads of the World," is a vibrant and bustling hub of entertainment, commerce, and culture in the heart of New York City. Known for its dazzling billboards, neon lights, and Broadway theaters, Times Square is a must-visit destination for visitors to the Big Apple. Tourists can soak in the electric atmosphere, shop at iconic stores like Macy\'s and Toys "R" Us, or catch a Broadway show at one of the district\'s historic theaters. With its lively street performers, bustling crowds, and iconic landmarks like the New Year\'s Eve Ball Drop, Times Square is a symbol of the energy and excitement of New York City.',
        ],
        lats:[34.048927, 40.7128,43.0760,36.518377919880905,40.7128],
        lngs:[-111.093735, -74.0060 ,-107.2903,  -119.91440041668248, -73.9855],
    },
    {
        id: '5',
        name: 'Japan',
        price: 10000,
        stars: 4.5,
        imageUrl: 'assets/images/Japan.jpg',
        backgroundUrl:'assets/images/BackgroundJapan.jpg',
        duration: "5 days",
        tags: ['Tokyo', 'Kyoto', 'Mount Fuji','Hiroshima Peace Memorial Park','Nara'],
        content: ["Tokyo: Tokyo, the bustling capital of Japan, is a vibrant metropolis known for its futuristic skyscrapers, historic temples, and bustling street markets. Visitors can explore iconic landmarks such as the Tokyo Tower, Senso-ji Temple, and Meiji Shrine, or indulge in shopping and dining in neighborhoods like Shibuya and Ginza. With its unique blend of modernity and tradition, Tokyo offers an unforgettable cultural experience.",
    
        "Kyoto: Kyoto, Japan's ancient capital, is renowned for its well-preserved temples, traditional tea houses, and scenic gardens. Visitors can immerse themselves in Japanese culture by exploring historic sites such as Kinkaku-ji (Golden Pavilion), Fushimi Inari Shrine, and Arashiyama Bamboo Grove. Kyoto's charming streets, lined with traditional machiya houses and cherry blossom trees, evoke a sense of timeless beauty and tranquility.",
    
        "Mount Fuji: Mount Fuji, Japan's highest peak, is an iconic symbol of natural beauty and spiritual significance. Located about 100 kilometers southwest of Tokyo, this majestic volcano offers breathtaking views of snow-capped peaks, pristine lakes, and lush forests. Visitors can hike to the summit, take scenic drives around its base, or enjoy boat cruises on nearby lakes such as Lake Kawaguchi and Lake Ashi. Mount Fuji's awe-inspiring presence has inspired artists, poets, and travelers for centuries.",
    
        "Hiroshima Peace Memorial Park: Hiroshima Peace Memorial Park, located in the heart of Hiroshima city, is a poignant reminder of the devastating atomic bombing that occurred during World War II. The park is home to the iconic A-Bomb Dome, a UNESCO World Heritage site, as well as numerous monuments, memorials, and museums dedicated to promoting peace and nuclear disarmament. Visitors can learn about the tragic history of Hiroshima, pay their respects to the victims of the bombing, and reflect on the importance of peace and reconciliation.",
    
        "Nara: Nara, Japan's first permanent capital, is famous for its ancient temples, serene gardens, and friendly deer that roam freely through the city's parks. Visitors can explore historic sites such as Todai-ji Temple, home to the Great Buddha statue, Kasuga Taisha Shrine, and Nara Park, where they can feed and interact with the resident deer. Nara's rich cultural heritage and natural beauty make it a must-visit destination for travelers seeking a glimpse into Japan's past."
    ],
        lats : [35.6764,35.0116,35.3606,34.3927,34.6851],
        lngs :[139.6500,135.7681,138.7274, 132.4522,135.8048],
    
    },
    {
        id: '6',
        name: 'Australia',
        price: 10000,
        stars: 4.5,
        imageUrl: 'assets/images/Australia.jpg',
        backgroundUrl:'assets/images/BackgroundAustralia.jpg',
        duration: "5 days",
        tags: ['Sydney Opera House', 'Great Barrier Reef', 'Uluru','Great Ocean Road','Kakadu National Park'],
        content: ["Sydney Opera House: The Sydney Opera House is one of Australia's most iconic landmarks, renowned for its distinctive sail-like design. Located on Sydney Harbour, this architectural masterpiece hosts opera, ballet, concerts, and other cultural performances. Visitors can take guided tours to explore its interior, including concert halls, theaters, and exhibition spaces, while enjoying panoramic views of the harbor and Sydney Harbour Bridge.",
    
        "Great Barrier Reef: The Great Barrier Reef, the world's largest coral reef system, is a UNESCO World Heritage site and a natural wonder of unparalleled beauty. Stretching over 2,300 kilometers along the Queensland coast, this marine paradise teems with vibrant coral reefs, exotic marine life, and crystal-clear waters. Visitors can snorkel, dive, or take scenic boat tours to explore its diverse ecosystems, encountering colorful coral gardens, tropical fish, sea turtles, and more.",
        
        "Uluru (Ayers Rock): Uluru, also known as Ayers Rock, is a sacred Aboriginal site and an iconic symbol of the Australian Outback. This massive sandstone monolith rises dramatically from the desert landscape, glowing red at sunrise and sunset. Visitors can hike around its base, learning about its cultural significance and admiring ancient rock art, while experiencing the awe-inspiring beauty and spiritual energy of this sacred site.",
        
        "Great Ocean Road: The Great Ocean Road is a breathtaking coastal drive that winds along Victoria's rugged coastline, offering stunning ocean views, dramatic cliffs, and natural landmarks. Highlights include the Twelve Apostles, a collection of limestone stacks rising from the Southern Ocean, as well as picturesque beaches, lush rainforests, and charming seaside towns. Visitors can embark on scenic drives, hike coastal trails, or simply relax and soak in the spectacular scenery along this iconic Australian road trip route.",
        
        "Kakadu National Park: Kakadu National Park, located in Australia's Northern Territory, is a UNESCO World Heritage site and a haven for nature lovers and outdoor enthusiasts. This vast wilderness area encompasses diverse landscapes, including wetlands, savannah woodlands, and ancient rock formations. Visitors can explore its rich biodiversity, spotting crocodiles, kangaroos, and birdlife, while discovering Aboriginal rock art sites that date back thousands of years. Kakadu offers opportunities for hiking, wildlife watching, cultural experiences, and immersive adventures in the heart of Australia's Top End."
    ],
     lats : [-33.856159, -18.2871, -25.3444,-38.7912,-13.0923],
     lngs : [151.2153, 147.6992, 131.0369, 143.5419,132.3938],


    },
    {
        id: '7',
        name: 'United Kingdom',
        price: 10000,
        stars: 4.5,
        imageUrl: 'assets/images/Uk.jpg',
        backgroundUrl:'assets/images/BackgroundUk.jpg',
        duration: "5 days",
        tags: ['Tower of London', 'London Eye', 'Stonehenge','Hyde Park','Loch Ness and Scottish Highlands'],
        content: ['Big Ben is the nickname for the Great Bell of the clock at the north end of the Palace of Westminster in London. The tower holds the largest four-faced chiming clock in the world and is a symbol of the United Kingdom and its capital city, London. It is renowned for its iconic architecture and historical significance, serving as a focal point for visitors and locals alike.',
        'The London Eye, also known as the Millennium Wheel, is a giant Ferris wheel situated on the South Bank of the River Thames in London. It offers breathtaking views of the city\'s skyline and landmarks, including Big Ben, the Houses of Parliament, and Buckingham Palace. The London Eye has become one of London\'s most popular tourist attractions, attracting millions of visitors each year.',
        'Stonehenge is a prehistoric monument located in Wiltshire, England. It consists of a ring of standing stones, each around 13 feet high, seven feet wide, and weighing around 25 tons. Archaeologists believe it was constructed from 3000 BC to 2000 BC. Stonehenge is a UNESCO World Heritage Site and one of the most famous landmarks in the United Kingdom.',
        'Hyde Park is one of the largest parks in London and a favorite retreat for both tourists and locals. Covering 350 acres, the park offers opportunities for leisurely strolls, picnics, and various recreational activities. Visitors can enjoy boating on the Serpentine lake, visit the Diana, Princess of Wales Memorial Fountain, or simply relax amidst lush greenery. Hyde Park hosts numerous events throughout the year, including concerts, festivals, and open-air theater performances.',
        'Loch Ness, located in the Scottish Highlands, is famous for its reputed resident, the Loch Ness Monster, also known as "Nessie." Besides monster hunting, the area offers breathtaking scenery, with rolling hills, ancient castles, and picturesque villages. Visitors can explore the rugged landscapes of the Scottish Highlands, embark on scenic drives, hike along stunning trails, or enjoy outdoor activities such as fishing, kayaking, and wildlife spotting. The region\'s rich history and folklore make it a captivating destination for travelers seeking adventure and natural beauty.',
    ],
        lats : [51.5007,51.5032, 51.1789, 51.5074,57.477772,],
        lngs : [0.1246,0.1195 , 1.8262, 0.1641,4.224721],
    },
    {
        id: '8',
        name: 'Thailand',
        price: 10000,
        stars: 4.5,
        imageUrl: 'assets/images/Thailand.jpg',
        backgroundUrl:'assets/images/BackgroundThailand.jpg',
        duration: "5 days",
        tags: ['Grand Palace, Bangkok', 'Wat Arun, Bangkok', 'Phi Phi Islands, Krabi','Chiang Mai Old City, Chiang Mai','Ayutthaya Historical Park, Ayutthaya'],
        content:['The Grand Palace in Bangkok is a magnificent complex of buildings that served as the official residence of the Kings of Siam. It houses several impressive structures, including the Wat Phra Kaew (Temple of the Emerald Buddha) and the Royal Reception Halls. Visitors can admire the intricate architecture, stunning murals, and exquisite decorations, reflecting Thailand\'s rich cultural heritage and royal history.',
                'Wat Arun, also known as the Temple of Dawn, is an iconic landmark situated on the banks of the Chao Phraya River. Its towering spires adorned with colorful porcelain tiles create a breathtaking sight, especially at sunrise and sunset. Visitors can climb the steep steps to the top of the central prang for panoramic views of Bangkok and the river.',
                'The Phi Phi Islands, located off the coast of Krabi, are renowned for their stunning natural beauty, turquoise waters, and pristine beaches. Visitors can enjoy snorkeling, diving, and sunbathing on the idyllic beaches, explore hidden coves and caves, and marvel at the breathtaking limestone cliffs rising from the sea. The islands\' picturesque landscapes have made them a popular filming location for movies and commercials.',
                'Chiang Mai Old City is a historic district surrounded by ancient walls and moats, preserving the city\'s rich cultural heritage. Visitors can wander through narrow streets lined with traditional wooden houses, explore ancient temples and monuments, and immerse themselves in the vibrant local culture. The area is known for its bustling markets, charming cafes, and lively street food scene, offering visitors a taste of authentic Thai cuisine and crafts.',
                'The Ayutthaya Historical Park, a UNESCO World Heritage site, is an ancient city dotted with ruins of temples, palaces, and statues dating back to the Ayutthaya Kingdom. Visitors can explore the sprawling complex on foot, marveling at the impressive architecture and intricate stone carvings. Highlights include the Wat Mahathat, known for its iconic Buddha head entwined in tree roots, and the towering prang of Wat Phra Si Sanphet.',
    ],
    lats : [13.7563,13.7563, 8.0855,18.7883 ,14.3692,],
    lngs : [100.5018,100.5018 , 98.9063, 98.9853,100.5877],
    },
    {
        id: '9',
        name: 'Greece',
        price: 10000,
        stars: 4.5,
        imageUrl: 'assets/images/Greece.jpg',
        backgroundUrl:'assets/images/BackgroundGreece.jpg',
        duration: "5 days",
        tags: ['Acropolis of Athens', 'Santorini', 'Delphi','Meteora','Mykonos'],
        content: ['The Acropolis of Athens is an ancient citadel located on a rocky outcrop above the city of Athens. It contains several ancient buildings of great architectural and historic significance, the most famous being the Parthenon, a temple dedicated to the goddess Athena.',
        'Santorini is a stunning island in the southern Aegean Sea, known for its whitewashed buildings, blue-domed churches, and breathtaking sunsets. Visitors can explore picturesque villages perched on cliffs, relax on beautiful beaches with crystal-clear waters, and indulge in delicious Greek cuisine.',
        'Delphi, located on the slopes of Mount Parnassus, was considered the center of the world in ancient Greece. It was home to the Oracle of Delphi, where visitors sought advice from the gods. Today, visitors can explore ancient ruins, including the Temple of Apollo and the Theatre of Delphi, while enjoying stunning mountain views.',
        'Meteora is a unique rock formation in central Greece, home to monasteries built on towering rock pillars. These monasteries, dating back to the 14th century, offer stunning views of the surrounding landscape and provide insight into the history of Orthodox Christianity in Greece.',
        'Mykonos is a popular island known for its vibrant nightlife, beautiful beaches, and charming Cycladic architecture. Visitors can wander through narrow streets lined with whitewashed buildings, relax on sandy beaches, and experience the island\'s lively atmosphere.',
    ],
    lats :[37.9715, 36.3932, 38.4825, 39.7212, 37.4467],
    lngs : [23.7265, 25.4615, 22.5004, 21.6308, 25.3289],
    },
    {
        id: '10',
        name: 'Egypt',
        price: 10000,
        stars: 4.5,
        imageUrl: 'assets/images/Egypt.jpg',
        backgroundUrl:'assets/images/BackgroundEgypt.jpg',
        duration: "5 days",
        tags: ['Pyramids of Giza', 'Luxor', 'Aswan','Abu Simbel Temples','Red Sea Riviera'],
        content: ["The Pyramids of Giza are ancient monuments located on the outskirts of Cairo. These iconic structures, including the Great Pyramid of Giza, are among the Seven Wonders of the Ancient World and attract millions of visitors each year. Visitors can explore the pyramids' intricate architecture, marvel at the Sphinx, and learn about ancient Egyptian history and culture.",
        "Luxor, often referred to as the world's greatest open-air museum, is home to a wealth of ancient Egyptian monuments and archaeological sites. Highlights include the Karnak Temple Complex, the Valley of the Kings, and the Temple of Hatshepsut. Visitors can immerse themselves in the rich history of ancient Egypt while exploring these magnificent sites.",
        "Aswan is a picturesque city located along the Nile River in southern Egypt. It is known for its beautiful riverfront promenade, vibrant markets, and historic landmarks such as the Philae Temple and the Aswan High Dam. Visitors can take a leisurely boat ride on the Nile, explore Nubian villages, and witness stunning sunsets over the river.",
        "The Abu Simbel Temples are two massive rock temples located near the border with Sudan. Built by Pharaoh Ramesses II in the 13th century BC, these temples are dedicated to the gods Ra-Horakhty, Ptah, and Amun. Visitors can marvel at the temples' colossal statues, intricate carvings, and stunning architecture.",
        "The Red Sea Riviera is a stunning coastal region known for its crystal-clear waters, vibrant coral reefs, and world-class diving and snorkeling opportunities. Popular destinations along the Red Sea coast include Sharm El Sheikh, Hurghada, and Dahab. Visitors can relax on beautiful beaches, explore underwater marine life, and enjoy a variety of water sports.",
    ],
     lats : [29.9792, 25.6872, 24.0889, 22.3372, 27.8770],
    lngs :[31.1342, 32.6396, 32.8998, 31.6236, 34.0467],

    },
    {
        id: '11',
        name: 'Brazil',
        price: 10000,
        stars: 4.5,
        imageUrl: 'assets/images/Brazil.jpg',
        backgroundUrl:'assets/images/BackgroundBrazil.jpg',
        duration: "5 days",
        tags: ['Christ the Redeemer, Rio de Janeiro', 'Iguazu Falls', 'Amazon Rainforest','Copacabana Beach, Rio de Janeiro','Pantanal Wetlands'],
        content: ["Christ the Redeemer is an iconic statue of Jesus Christ located atop the Corcovado mountain in Rio de Janeiro. Offering panoramic views of the city, this majestic monument is one of the New Seven Wonders of the World and a symbol of Brazilian culture and Christianity.",
        "Iguazu Falls is a breathtaking natural wonder situated on the border between Brazil and Argentina. With its cascading waterfalls surrounded by lush rainforest, Iguazu is one of the largest and most impressive waterfall systems in the world. Visitors can explore the falls via hiking trails, boat rides, and helicopter tours, marveling at its sheer beauty and power.",
        "The Amazon Rainforest, the largest tropical rainforest in the world, is a biodiversity hotspot teeming with unique flora and fauna. Spanning nine countries, including Brazil, the Amazon is home to countless species of plants and animals, many of which are found nowhere else on Earth. Visitors can embark on guided tours, river cruises, and jungle treks to explore this incredible ecosystem.",
        "Copacabana Beach is one of the most famous beaches in the world, known for its golden sands, vibrant atmosphere, and scenic views. Stretching for 4 kilometers along the Atlantic coast, Copacabana offers plenty of opportunities for swimming, sunbathing, and people-watching. Visitors can also enjoy beach volleyball, surfing, and sampling delicious Brazilian cuisine at the nearby kiosks and restaurants.",
        "The Pantanal is the world's largest tropical wetland, renowned for its rich biodiversity and abundant wildlife. Located primarily in Brazil, this vast floodplain is home to jaguars, caimans, capybaras, and countless bird species. Visitors can explore the Pantanal on guided safaris, boat tours, and horseback rides, immersing themselves in the natural beauty and tranquility of this unique ecosystem.",
        ],
        lats : [ -22.9519, -25.6866, -3.1190, -22.9717, -18.1324],
        lngs : [-43.2105, -54.4444, -60.0253, -43.2175, -57.7352],
    
    },
    {
        id: '12',
        name: 'Switzerland (Swiss)',
        price: 10000,
        stars: 4.5,
        imageUrl: 'assets/images/Swiss.jpg',
        backgroundUrl:'assets/images/BackgroundSwiss.jpg',
        duration: "5 days",
        tags: ['Zermatt', 'Lucerne', 'Interlaken','Geneva','Jungfraujoch'],
        content: ["Zermatt is a charming mountain village nestled in the Swiss Alps, renowned for its stunning views of the Matterhorn peak. Visitors can enjoy world-class skiing and snowboarding in the winter, as well as hiking and mountain biking in the summer. The village is car-free, adding to its picturesque charm, and offers a range of luxury hotels, gourmet restaurants, and boutique shops.",
        "Lucerne, located in the heart of Switzerland, is a picturesque city surrounded by mountains and lakes. Visitors can explore its well-preserved medieval architecture, including the iconic Chapel Bridge and Water Tower, stroll along the scenic promenades by Lake Lucerne, or take a leisurely boat cruise to enjoy panoramic views of the Alps.",
        "Interlaken is a popular resort town situated between Lake Thun and Lake Brienz, offering breathtaking views of the Jungfrau mountain range. Visitors can experience thrilling outdoor activities such as paragliding, skydiving, and white-water rafting, or take leisurely boat rides on the crystal-clear lakes. The town also serves as a gateway to the nearby Jungfrau region, known for its stunning alpine landscapes and hiking trails.",
        "Geneva is a cosmopolitan city located on the shores of Lake Geneva, known for its rich history, cultural diversity, and international organizations. Visitors can explore historic landmarks such as the Jet d'Eau fountain and St. Pierre Cathedral, stroll through the picturesque Old Town, or visit world-class museums and art galleries. The city also offers beautiful parks, lakeside promenades, and vibrant nightlife.",
        "Jungfraujoch, often referred to as the 'Top of Europe,' is a spectacular mountain pass accessible by cogwheel train from Interlaken. At an elevation of 3,454 meters, it offers breathtaking views of the surrounding Swiss Alps, including the Eiger, Mönch, and Jungfrau peaks. Visitors can explore the Ice Palace, walk along the Glacier Plateau, or enjoy panoramic vistas from the observation deck.",
    ],
    lats : [46.0207, 47.0502, 46.6867, 46.2044, 46.5476],
    lngs : [7.7491, 8.3093, 7.8633, 6.1432, 7.9086],
    },
    {
        id: '13',
        name: 'Hong Kong',
        price: 10000,
        stars: 4.5,
        backgroundUrl:'assets/images/BackgroundHongkong.jpg',
        imageUrl: 'assets/images/Hongkong.jpg',
        duration: "5 days",
        tags: ['Victoria Peak', 'Hong Kong Disneyland', 'Ngong Ping 360','Ocean Park Hong Kong','Lan Kwai Fong'],
        content: ["Victoria Peak is the highest point on Hong Kong Island, offering stunning panoramic views of the city skyline, Victoria Harbour, and surrounding islands. Visitors can reach the peak via the historic Peak Tram or hike along scenic trails. At the summit, they can enjoy attractions such as Sky Terrace 428 and Peak Tower, as well as dining and shopping options.",
        "Hong Kong Disneyland is a magical theme park located on Lantau Island, offering a world of fantasy, adventure, and entertainment for visitors of all ages. From classic Disney attractions and beloved characters to thrilling rides and immersive experiences, the park promises a memorable adventure for families and Disney fans alike.",
        "Ngong Ping 360 is a scenic cable car ride that takes visitors on a breathtaking journey across Lantau Island. As they soar above lush mountains, pristine beaches, and picturesque villages, passengers can admire panoramic views of the surrounding landscape. At Ngong Ping Village, they can explore cultural attractions, enjoy delicious food, and visit the iconic Tian Tan Buddha.",
        "Ocean Park Hong Kong is a world-class marine theme park offering a diverse range of attractions, including thrilling rides, animal exhibits, and live shows. Visitors can experience the excitement of roller coasters, meet adorable pandas, and marvel at underwater wonders in expansive aquariums. With interactive experiences and educational programs, Ocean Park provides fun and learning for visitors of all ages.",
        "Lan Kwai Fong is a vibrant nightlife district in Central, known for its lively atmosphere, bustling streets, and diverse entertainment options. Visitors can explore a wide range of bars, clubs, and restaurants, enjoying delicious food, refreshing drinks, and live music late into the night. Whether you're looking for a fun night out with friends or a memorable party experience, Lan Kwai Fong has something for everyone.",
    ],
    lats: [22.2757, 22.3167, 22.2525, 22.2467, 22.2806],
    lngs : [114.1496, 114.0452, 113.9047, 114.1750, 114.1540],
        },
    {
        id: '14',
        name: 'Bali',
        price: 10000,
        stars: 4.5,
        backgroundUrl:'assets/images/BackgroundBali.jpg',
        imageUrl: 'assets/images/Bali.jpg',
        duration: "5 days",
        tags: ['Ubud Monkey Forest', 'Tanah Lot Temple', 'Tegallalang Rice Terraces','Kuta Beach','Uluwatu Temple'],
        content:["Ubud Monkey Forest is a nature reserve and Hindu temple complex located in Ubud, Bali. It is home to over 700 long-tailed macaques, which roam freely within the sanctuary. Visitors can explore lush jungle trails, ancient temples, and serene waterfalls while observing the playful antics of the monkeys.",
        "Tanah Lot Temple is a Hindu temple situated on a rock formation off the coast of Bali. It is one of the most iconic landmarks in Bali, known for its breathtaking sunset views and stunning ocean scenery. Visitors can explore the temple grounds, watch traditional Balinese dance performances, and admire the beauty of the surrounding landscape.",
        "Tegallalang Rice Terraces are stunning landscapes of stepped rice fields located in the heart of Bali. These picturesque terraces offer panoramic views of lush greenery, coconut palms, and traditional Balinese villages. Visitors can take leisurely walks through the rice fields, interact with local farmers, and capture stunning photographs of the scenic beauty.",
        "Kuta Beach is one of the most popular beaches in Bali, renowned for its golden sands, rolling waves, and vibrant atmosphere. It is a hub for water sports such as surfing, snorkeling, and parasailing, attracting surfers and beachgoers from around the world. Visitors can relax on the beach, enjoy breathtaking sunsets, and experience Bali's famous nightlife.",
        "Uluwatu Temple is a cliffside Hindu temple perched atop a rugged limestone cliff overlooking the Indian Ocean. It is renowned for its stunning ocean views, traditional Balinese architecture, and captivating Kecak dance performances. Visitors can explore the temple complex, witness breathtaking sunsets, and marvel at the natural beauty of the surrounding coastline.",
    ],
    lats : [-8.5197, -8.6213, -8.4250, -8.7237, -8.8235],
    lngs : [115.2595, 115.0868, 115.2768, 115.1695, 115.0864],
    },
    {
        id: '15',
        name: 'Dubai',
        price: 10000,
        stars: 4.5,
        backgroundUrl:'assets/images/BackgroundDubai.jpg',
        imageUrl: 'assets/images/Dubai.jpg',
        duration: "5 days",
        tags: ['Burj Khalifa', 'The Dubai Mall', 'Palm Jumeirah','Dubai Marina','The Dubai Fountain'],
        content: ["The Burj Khalifa is the tallest building in the world, standing at a height of 828 meters. Visitors can take high-speed elevators to the observation decks on the 124th and 148th floors, offering panoramic views of the city skyline and the Arabian Gulf.",
        "The Dubai Mall is one of the largest shopping malls in the world, featuring over 1,200 retail outlets, including luxury brands, fashion boutiques, and department stores. Visitors can also explore attractions such as the Dubai Aquarium and Underwater Zoo, the Dubai Ice Rink, and the VR Park.",
        "Palm Jumeirah is an artificial archipelago shaped like a palm tree and is one of Dubai's most iconic landmarks. Visitors can relax on pristine beaches, enjoy water sports, dine at luxury resorts and hotels, and take in stunning views of the city skyline and the Arabian Gulf.",
        "Dubai Marina is a vibrant waterfront district known for its stunning skyline, luxury yachts, and upscale dining and entertainment options. Visitors can stroll along the marina promenade, take a boat cruise, or dine at one of the many restaurants overlooking the water.",
        "The Dubai Fountain is a captivating musical fountain located at the base of the Burj Khalifa. Visitors can watch as water jets dance to music and lights in choreographed performances set against the backdrop of the iconic skyscraper, creating a mesmerizing spectacle.",
    ],
    lats : [25.1972, 25.1974, 25.1125, 25.0673, 25.1959],
    lngs : [55.2744, 55.2791, 55.1396, 55.1403, 55.2760],
    },
    {
        id: '16',
        name: 'Abu Dhabi',
        price: 10000,
        stars: 4.5,
        backgroundUrl:'assets/images/BackgroundAbudhabhi.jpg',
        imageUrl: 'assets/images/Abudhabhi.jpg',
        duration: "5 days",
        tags: ['Sheikh Zayed Grand Mosque', 'Louvre Abu Dhabi', 'Ferrari World Abu Dhabi','GenevaYas Marina Circuit','Qasr Al Watan'],
        content: ["The Sheikh Zayed Grand Mosque is one of the largest mosques in the world, featuring stunning architecture, intricate designs, and beautiful marble work. Visitors can admire its grandeur, explore its vast prayer halls, and marvel at the intricate details of its domes, minarets, and courtyards.",
        "The Louvre Abu Dhabi is a world-renowned museum that showcases art and artifacts from around the globe. Visitors can admire masterpieces from various civilizations, including ancient artifacts, classical sculptures, and modern artworks, all housed in a stunning architectural masterpiece designed by Jean Nouvel.",
        "Ferrari World Abu Dhabi is a thrilling theme park dedicated to the iconic Italian car brand. Visitors can experience adrenaline-pumping rides, including the world's fastest roller coaster, explore interactive exhibits, and enjoy family-friendly entertainment and dining options.",
        "Yas Marina Circuit is a world-class motorsport venue and home to the Formula 1 Abu Dhabi Grand Prix. Visitors can experience the thrill of driving on the same track as F1 champions, enjoy guided tours of the circuit, and participate in various motorsport activities and events.",
        "Qasr Al Watan, also known as the Presidential Palace, is a stunning architectural marvel that serves as the official seat of the UAE government. Visitors can explore its opulent interiors, admire its intricate Islamic design elements, and learn about the country's governance and heritage through interactive exhibits and guided tours.",
    ],
    lats :[24.4120, 24.5333, 24.4849, 24.4670, 24.4122],
    lngs : [54.4746, 54.3797, 54.6038, 54.6055, 54.4347],
    },

]

export const Sample_users: any[]=[
    {
        name:"Preetham Reddy",
        email:"preetham@gmail.com",
        password:"3737",
        address:"Warangal",
        isAdmin:true,
        phone:'8187006161',
    },
    {
        name:"Manaideep",
        email:"gamestar@gmail.com",
        password:"0369",
        address:"Warangal",
        isAdmin:false,
        phone:'7842242865',
    }
]